export const LOGIN = "LOGIN",
  REGISTER = "REGISTER",
  RESET_PASSWORD = "RESET_PASSWORD",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  LOGOUT = "LOGUT",
  UPDATE_CONTAINERS = "UPDATE_CONTAINERS",
  FETCH_RECIPES = "FETCH_RECIPES";